### ISSUE TITLE
autoconf

### ISSUE THREAD

**Issue by androclus** [NalaGinrut/guile-csv#1]
hey, nala.. thank you for this guile csv package.. i am interested in getting it going.

i did a git clone, and then i noticed:

1) the README and INSTALL files refer to doing a:

./configure && make

but ./configure does not work unless autoconf has been run first.. so  I am wondering if (for instance) the README file should add an instruction to use autoconf?  e.g.,

autoconf
./configure && make

?

2) When I try running autoconf (I have version 2.69 on Kubuntu 15.04), it DOES create a "configure" file, but I get the following error message:

$ autoconf
configure.ac:25: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:26: error: possibly undefined macro: AM_SILENT_RULES
$ _

**Comment by NalaGinrut** [comment]
@jastern Seems configure was added to .gitignore unreasonably. I've fixed it and updated configure.ac . It's released as 0.0.3, please try it.

**Comment by androclus** [comment]
@NalaGinrut thank you. after a git pull i can now run _./configure_.  but it does not finish successfully because it cannot find files _build-aux/missing_ and _build-aux/config.sub_:

```
$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
/bin/sh: 0: Can't open /home/jastern/opt/guile-csv/build-aux/missing
configure: WARNING: 'missing' script is too old or missing
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
configure: checking for guile 2.2
configure: checking for guile 2.1
configure: checking for guile 2.0
configure: found guile 2.0
checking for GUILE... yes
checking for guile-config... /usr/bin/guile-config
checking for guile... /usr/bin/guile
checking for guile-config... /usr/bin/guile-config
checking for guile-tools... /usr/bin/guile-tools
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... -std=gnu11
checking dependency style of gcc -std=gnu11... none
configure: error: cannot run /bin/sh build-aux/config.sub
$ _
```

**Comment by NalaGinrut** [comment]
@jastern I've updated something, please try the latest commit

**Comment by androclus** [comment]
@nala thanks.  ./configure now works, so it's a step better.

however, the next step ('make') still fails:

```
$ make
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /home/jastern/opt/guile-csv/build-aux/missing --run aclocal-1.12 -I build-aux
/home/jastern/opt/guile-csv/build-aux/missing: 51: /home/jastern/opt/guile-csv/build-aux/missing: aclocal-1.12: not found
WARNING: 'aclocal-1.12' is missing on your system.  You should only need it if
         you modified 'acinclude.m4' or 'configure.ac'.  You might want
         to install the Automake and Perl packages.  Grab them from
         any GNU archive site.
 cd . && /bin/sh /home/jastern/opt/guile-csv/build-aux/missing --run automake-1.12 --gnu
/home/jastern/opt/guile-csv/build-aux/missing: 51: /home/jastern/opt/guile-csv/build-aux/missing: automake-1.12: not found
WARNING: 'automake-1.12' is missing on your system.  You should only need it if
         you modified 'Makefile.am', 'acinclude.m4' or 'configure.ac'.
         You might want to install the Automake and Perl packages.
         Grab them from any GNU archive site.
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /home/jastern/opt/guile-csv/build-aux/missing --run autoconf
configure.ac:26: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:27: error: possibly undefined macro: AM_SILENT_RULES
Makefile:326: recipe for target 'configure' failed
make: *** [configure] Error 1
$
```

But i do have aclocal (v1.14.1) and automake (v1.14.1)

And I don't know how to fix the undefined macro.

thanks

**Comment by NalaGinrut** [comment]
@jastern I've simplified install stuffs, it's unnecessary to use autoconf/automake for such simple project. Please try it again.

**Comment by androclus** [comment]
@nala - that seemed to do it.. up and running now, thanks.
